### ISSUE TITLE
Pick the future days only or not limit

### ISSUE THREAD

**Issue by Xeriou** [puranjayjain/md-date-time-picker#110]
HI , 

now this project seem to can pick past day only..

can this project pick the future day only??

or not limit for pick.

**Comment by puranjayjain** [comment]
@Xeriou you can set the future date according to your own need in the configuration. 
See https://puranjayjain.github.io/md-date-time-picker/#documentation/future

**Comment by Xeriou** [comment]
@puranjayjain

OHH!!!!  THANKS....

I just forgot to visit official site :P
