### ISSUE TITLE
date format

### ISSUE THREAD

**Issue by rebornishard** [puranjayjain/md-date-time-picker#116]
# Format for date

i tried toDateString() , toLocaleDateString()
.toString('yyyy-MM-dd') , getDate() , getMonth() , getYear()
none work,

how to make it become mm-dd-yyyy or yyyy-mm-dd ?
thanks

**Comment by rebornishard** [comment]
close this, my fault, moment js did the job

**Comment by AkhilaErrabelly** [comment]
I'm having the same issue. Can you please share how format for date worked? @rebornishard
