### ISSUE TITLE
cannot import Draggabilly because of case sensitive require

### ISSUE THREAD

**Issue by rbaumi** [puranjayjain/md-date-time-picker#119]
In md-date-time-picker you have a statement:

`import Draggabilly from 'Draggabilly'`

which translates to `require('Draggabilly')`. The problem is that it throws an error:

>  cannot resolve module 'Draggabilly'

because the library name should be lowercase. Manually changing to `require('draggabilly')` in dist folder solves the issue.

**Comment by puranjayjain** [comment]
will fix this issue asap

**Comment by phota** [comment]
@puranjayjain - I am using your library and getting the same error. Could you please fix this.

**Comment by puranjayjain** [comment]
Really getting a time constrains these days but i'll try to do it soon

**Comment by im-n1** [comment]
Just ran into this. I tried to use whole library in old-school style and include it as script to my HTML. Still gegging strange errors.

**Comment by puranjayjain** [comment]
I'll change the name to lowercase to fix this problem in the next build. It seems to solve the problem. Thank you for your help @rbaumi

**Comment by arabsight** [comment]
awesome component, can we expect this to be fixed (since its just one letter change). can't use with aurelia-cli (uses amd).

**Comment by puranjayjain** [comment]
I'm currently on a vacation so it won't probably be until next year. But I expect it will be resolved by next year 😄

**Comment by arabsight** [comment]
cool, thanks

**Comment by tytskyi** [comment]
npm version is behind others, npm still contains code with `Draggabilly` string

**Comment by puranjayjain** [comment]
thanks @tytskyi bumped to v2.3.0 on npm

**Comment by tytskyi** [comment]
@puranjayjain thank you, this now works as expected. I think issue is resolved. 
cc @rbaumi
