### ISSUE TITLE
Draggabilly integration doesn't seem to work on mobile devices

### ISSUE THREAD

**Issue by dmott** [puranjayjain/md-date-time-picker#131]
Using the chrome inspector with device emulation turned on, through Safari in the iOS Simulator (Bundled with XCode, on OS X), as well as on various Android and iOS physical devices, dragging the minute hand of the Time Picker, the dragging functionality doesn't seem to work.

This issue is present on the example page when you click "Toggle Time Dialog" at https://puranjayjain.github.io/md-date-time-picker/

**Comment by puranjayjain** [comment]
Yes i am aware of that issue and there is a need to add more fixes for  mobile devices. I'll start work on it sometime in November (no promises though)

**Comment by puranjayjain** [comment]
This has been fixed in the latest release. Please reopen this issue or open another if it appears along with a demo link.
