### ISSUE TITLE
Close the calendar by clicking outside

### ISSUE THREAD

**Issue by alegag** [puranjayjain/md-date-time-picker#141]
Would it break the MD guidelines if we were to implement a "close calendar when clicking on the page" ?

What I mean, if I hope the calendar and want to dismiss it, by clicking anywhere else on the page (but the calendar), it would close it.

Maybe we should activate that option only when "autoClose=true".

@puranjayjain Let me know what you think !

**Comment by puranjayjain** [comment]
I think it's a good option and does not violate md guidelines. We should implement it

**Comment by alegag** [comment]
@puranjayjain It has been added now, in the PR.
