### ISSUE TITLE
how do you get the selected date from the onOk event? Docs are wrong.

### ISSUE THREAD

**Issue by tdfairbrother** [puranjayjain/md-date-time-picker#152]
In your documentation, it has the following example for handling the ok event. In the example below, I can't see where x comes from.

```
    // assuming test1 is an input text element
            document.getElementById('test1').addEventListener('onOk', function() {
              this.value = x.time.toString();
            });

```

I have looked through the code and it uses a custom event but the custom event doesn't have any type of date/value payload.

```
	_attachEventHandlers() {
		let me = this
		let ok = this._sDialog.ok
		let cancel = this._sDialog.cancel
		// create cutom events to dispatch
		let onCancel = new CustomEvent('onCancel')
		let onOk = new CustomEvent('onOk')
		cancel.onclick = function() {
			me.toggle()
			if (me._trigger) {
				me._trigger.dispatchEvent(onCancel)
			}
		}
		ok.onclick = function () {
			me._init = me._sDialog.sDate
			me.toggle()
			if (me._trigger) {
				me._trigger.dispatchEvent(onOk)
			}
		}
	}
```

How do you get the selected date from the onOk event?

**Comment by tdfairbrother** [comment]
I have been searching for ages but only found the answer when I posted above. I didn't see the section `You can get or set the current time of the dialog.`

`var time = dialog.time;`

Seems weird that you have to go back to the date picker instance to get the selected value. Also the docs are still confusing in referencing `x`

**Comment by puranjayjain** [comment]
Seems to be a docs issue shall fix it. But x is the time picker's instance.

**Comment by tdfairbrother** [comment]
> But x is the time picker's instance.

I guessed that but it is not clear. 
x is not assigned anywhere in your docs.

**Comment by puranjayjain** [comment]
@tdfairbrother will fix that in the docs

**Comment by MelleB** [comment]
@puranjayjain Thanks a lot for your lib!

Maybe this helps somebody, or maybe it's a useful addition to the docs:

	function registerDateTimePicker(elementId, picker, fmt) {
		let element = document.getElementById(elementId);
		element.addEventListener('click', function(e) {
			picker.trigger = element;
			picker.toggle();
		});
		element.addEventListener('onOk', function(e) {
			// Maybe mention picker.time is a moment object, which you can format()
			this.value = picker.time.format(fmt);
			// Integration with MDL
			this.parentNode.MaterialTextfield.checkDirty();
		});
	}

**Comment by timboctwo** [comment]
Is there a way to change the date return format?

```
 z.trigger = document.getElementById('test1');
     document.getElementById('test1').addEventListener('onOk', function() {
       this.value = z.time.toString();
     });
```
Nevermind, I just look in the code that "z.time" is a moment object. I just add `z.time.format('L').toString();` and does the trick.
