### ISSUE TITLE
usage with webpack

### ISSUE THREAD

**Issue by digitalkaoz** [puranjayjain/md-date-time-picker#16]
im trying to use your awesome work in my project, but im failing hard...

im using webpack and babel for use of es6...

none of these methods worked for me :/

``` js
import 'md-date-time-picker/dist/js/md-date-time-picker';
var mdDateTimePicker = require('md-date-time-picker/dist/js/md-date-time-picker');
import mdDateTimePicker from 'md-date-time-picker/dist/js/md-date-time-picker';
```

i see you are not exporting a `default` in your js, maybe thats the problem, but i think importing the `dist` version should work then...

any help is appreciated!

**Comment by puranjayjain** [comment]
@digitalkaoz I know about that problem with the project in it's state doesnt support webpack, amd, commonjs, es6 modules system. However, I'm trying to support it. I'll add support for it in the next minor release. Give me a time of 3 days (at max). Meanwhile if you have any suggestions or a quick way send a pr :smile:

**Comment by digitalkaoz** [comment]
i currently fiddeling around a bit a need to dig into a bit more, ping me if you have something working

**Comment by digitalkaoz** [comment]
@puranjayjain any news?

**Comment by puranjayjain** [comment]
@digitalkaoz it will be done today am working on it and running some tests

**Comment by digitalkaoz** [comment]
:-*

**Comment by puranjayjain** [comment]
@digitalkaoz can you try the latest build (not released just pull from the master branch) and tell if it works for you? that'll be great

**Comment by digitalkaoz** [comment]
works like a charm...but it seems its not applying the choosen Date/Time back to the Input Field? Guess i have to implement this tiny piece myself?

**Comment by puranjayjain** [comment]
@digitalkaoz  It should work or perhaps I think it has some problem in my implementation? Please suggest I am pretty new to webpack. Btw how are using the modules -> requirejs or browserify or something else. 

Now a new problem has arised with the module, it works with amd/umd/what not but not with simple globals in browser. So I am splitting the js folder into globals and modules and also adding the same on the docs.

Any more suggestions would be welcome or shall I proceed with this approach?

**Comment by puranjayjain** [comment]
@digitalkaoz also tell me if you are able to implement it with the input field :grin:

**Comment by digitalkaoz** [comment]
i think this might be a good template for non es6 usage: https://github.com/umdjs/umd/blob/master/templates/jqueryPlugin.js

i use it like that:

``` js
import mdDateTimePicker from 'md-date-time-picker/src/js/mdDateTimePicker';

function initializeDatepicker() {
    var dialog = new mdDateTimePicker({
        type: 'date',
        future: moment().add(21, 'years')
    });

    var fields = document.querySelectorAll('input[type="date"]');

    Array.prototype.forEach.call(fields, (field) => {
        field.addEventListener('onOk', function() {
            field.value = x.time().toString();
        });
        field.addEventListener('click', function () {
            dialog.toggle();
        });
    });
}

initializeDatepicker();
```

in my case the `onOk` isnt triggered :/

**Comment by digitalkaoz** [comment]
this works:

``` js
function initializeDatepicker() {

    var fields = document.querySelectorAll('input[type="date"], input.date');

    Array.prototype.forEach.call(fields, (field) => {
        var dialog = new mdDateTimePicker({
            type: 'date',
            future: moment().add(21, 'years'),
            trigger: field
        });

        field.addEventListener('onOk', (e) => {
            field.value = dialog.time().format('L');
        });
        field.addEventListener('click', function () {
            dialog.toggle();
        });
    });
}
```

so this must be reflected in the docs ;)

**Comment by digitalkaoz** [comment]
@puranjayjain did you published it already on npm?

**Comment by puranjayjain** [comment]
@digitalkaoz sorry didnt get the time this week. I'll try to publish in a day but i'll be sticking to your implementation so you can continue to use it :smile:

**Comment by puranjayjain** [comment]
@digitalkaoz fixed and published the issue, also updating the docs now feel free to close/reopen the issue after testing it.

**Comment by puranjayjain** [comment]
sorry forgot to close the issue

**Comment by digitalkaoz** [comment]
@puranjayjain its not really fixed, as you commented out the important `export default` but ill try to wrap it in a UMD so the compiling to a dist-build will succeed

**Comment by puranjayjain** [comment]
@digitalkaoz oh :sob: although I left a comment above it for users using es6. Right now es6 can't be compiled directly to umd + globals format together (or that I might not be knowing of any such methods). Any suggestions on how to proceed? Although the umd build (in dist) was compiled with export default and the globals one without it.

**Comment by puranjayjain** [comment]
:tada: found a possible solution http://jspm.io/

**Comment by digitalkaoz** [comment]
yeah if i have a free evening i could look into solving this.

i thought babel could solve this and provide a solution for all platforms, sadly not?! i dont know jspm, but it looks like it could handle that?!

**Comment by puranjayjain** [comment]
unfortunately babel alone wasn't able to solve it :disappointed: but jspm looks promising trying it now

**Comment by puranjayjain** [comment]
@digitalkaoz check the latest build it has been fixed (finally or so I think). The build is now in the default folder of dist/js with support all of umd + amd + global :tada: please try it. 
Also the version will be bumped to 2.0.0 as we are following semver and don't want the users to get angry for breaking api as this version introduces breaking changes in api.

**Note**: now the es6 exports is followed from babel so the require statement might change.
Also some functions are also changed such as trigger and time. They now follow get and set from es6 (usage in demo.html)

Please report your findings as this issue must be resolved sooner as it is a major barrier to entry.

**Comment by puranjayjain** [comment]
v2.0.0 released as always, reopen this issue or open a new one for problems

**Comment by digitalkaoz** [comment]
merci :)

**Comment by jagadeeshagm** [comment]
This date picker is not working in IE 8 to 11. Can someone suggest the solution for this

https://puranjayjain.github.io/md-date-time-picker/
