### ISSUE TITLE
show date/time pickers modal

### ISSUE THREAD

**Issue by SabineMa** [puranjayjain/md-date-time-picker#176]
Hi,
thank you for your awesome date/time pickers. 
One question: how can I show them modal?
(Editing all "behind" the picker not possible, only ok and cancel possible...)
I did not find anything about it in the docs.
Regards
Sabine

**Comment by puranjayjain** [comment]
You're welcome 😄 
"how can I show them modal?" I quite didn't get this? What do you mean by them modal? 😕 
Please elaborate or give an example.

**Comment by SabineMa** [comment]
Sure.
After calling the date or time dialog, I want that all which is behind the  date or time dialog can not be edited. Please see the screenshot below. I opened the dialog but it is possible to write in the time entry field. It would be also possible to click in the other date and time fields and to open several dialogs.


![bildschirmfoto 2016-12-22 um 10 54 05](https://cloud.githubusercontent.com/assets/13763544/21421791/ff504ddc-c834-11e6-9533-10f4bf4a6eb0.png)

I want the date/time dialogs opening like my other dialogs - nothing editable except the two buttons in the dialog. See example for my logoff:
![bildschirmfoto 2016-12-22 um 10 57 28](https://cloud.githubusercontent.com/assets/13763544/21421944/b25a3fa0-c835-11e6-97fc-075f30c09550.png)

**Comment by SabineMa** [comment]
sorry for closing, wrong button :-)

**Comment by puranjayjain** [comment]
Ok, so you want the picker to behave like a modal window, which closes on outside click or prevents clicks outside. That feature was in works in  #140. Not tested it though but I believe it should work.

**Comment by SabineMa** [comment]
Thanks. I don't want it to close when the user clicks outside. But I think I will manage it by putting a modal div in it when opening and removing the div when selecting or cancel.
