### ISSUE TITLE
UX Timeline Delay switch and don't autoswitch from minute back to hour

### ISSUE THREAD

**Issue by codingfriend1** [puranjayjain/md-date-time-picker#181]
From a UX standpoint when I'm in the hour view and I click an hour I expect to see the needle jump to that position before switching to the minute view. Also I find it unintuitive that the minute view would jump back to the hour view when finished automatically. Otherwise it feels like it's selecting a time I didn't choose because you don't realize it's switched back to hour. If a user wants to go back to the hour it it intuitive enough where they can just click on the hour view.

**Comment by puranjayjain** [comment]
@codingfriend1 what you say is correct but I chose to go with the UX mentioned in material design specification where the sample video shows the exact same behavior and hence that.
