### ISSUE TITLE
Draggabilly not optional

### ISSUE THREAD

**Issue by Codebreaker101** [puranjayjain/md-date-time-picker#196]
It's mentioned [HERE](https://github.com/puranjayjain/md-date-time-picker#draggabilly) that the Draggabilly is an optional dependency, but when not including it javascript returns an error `_Draggabilly2.default is not a constructor`  and the window doesn't open. 

As far as I'm aware there is no flag to set to disable or enable the usage of Draggabilly

**Comment by illright** [comment]
I can't even run the demo on Firefox Ubuntu. The `draggabilly` JS file seems to be included, but the clock popup doesn't appear. Everything's fine with the date, though

**Comment by puranjayjain** [comment]
This has been fixed in the latest release. Please reopen this issue or open another if it appears along with a demo link.
