### ISSUE TITLE
Images not found if using a theme

### ISSUE THREAD

**Issue by cmfcmf** [puranjayjain/md-date-time-picker#2]
Hi @puranjayjain!

First of all: Thank you for this _really awesome library_!

The image paths inside the theme files are incorrect. It says: `../images/ic_keyboard_arrow_left_black_24px.svg`, which would work for the base css, but doesn't work for themes, as they are deeper down the directory structure.

**Comment by puranjayjain** [comment]
@cmfcmf thanks for the feedback! If you are using a theme why not just replace the correct theme file from the folder into the root directory instead? e.g I want to use the deep-purple theme in light mode so i'll copy it from css/theme/dark/deep-purple/here to css/here

**Comment by puranjayjain** [comment]
@cmfcmf I'm also adding themes to the docs so you'll be able to click and download the theme and how to use it will also be written there

**Comment by cmfcmf** [comment]
> @cmfcmf thanks for the feedback! If you are using a theme why not just replace the correct theme file from the folder into the root directory instead? e.g I want to use the deep-purple theme in light mode so i'll copy it from css/theme/dark/deep-purple/here to css/here

Ahh I see. Thank you for the clarification.

> @cmfcmf I'm also adding themes to the docs so you'll be able to click and download the theme and how to use it will also be written there

Thanks! I'm guessing I was a little to early then. :smile: If it's going to be documented then it's all good :+1:
