### ISSUE TITLE
How to import this to angular ?

### ISSUE THREAD

**Issue by hamzahamidi** [puranjayjain/md-date-time-picker#217]
# Issue Templates

- Search the currently opened issues and past issues before posting a new one.
- Escalate issues by making a reaction of :+1: at the first comment on the issue (the issue author's)
- Be clear and try to open an issue with one problem at a time (open multiple issues if you have multiple problems)

**Comment by hamzahamidi** [comment]
And  where the hell is mdDateTimePicker.css located ?

**Comment by puranjayjain** [comment]
@hamzahamidi its in `dist/css` folder . If this was the issue I'm closing it feel free to reopen or open another one in the future for problems. Thank you!

**Comment by hamzahamidi** [comment]
What's the event triggered when a valid date or time is selected successfully?

**Comment by puranjayjain** [comment]
Please refer to the documentation for that
https://puranjayjain.github.io/md-date-time-picker/#documentation/onOk

**Comment by hamzahamidi** [comment]
When I click double time on the clock component It shows 0Undefined. What is the variable you add to minutes that shows undefined ? Is the 0 reset necessary in your code ? Im trying to use this plugin in a hybride mobile application and this error is frequent.

**Comment by puranjayjain** [comment]
I didn't get you here

**Comment by hamzahamidi** [comment]
![capture](https://user-images.githubusercontent.com/22576950/28368200-d6bc6140-6c93-11e7-88ec-74c1bce73216.PNG)
When you click multiple times on minuteView you obtain this error its frequent on mobile

**Comment by puranjayjain** [comment]
@hamzahamidi can you repost the above in a separate issue? It will make it easier to track it. This seems to be another race condition

**Comment by hamzahamidi** [comment]
Race condition indeed
