### ISSUE TITLE
Only allow "sharp" times to be selected

### ISSUE THREAD

**Issue by XcrossD** [puranjayjain/md-date-time-picker#223]
Is it possible to set the time picker to allow only "sharp" times to be picked by the user? For example, 1 sharp, 2 sharp, 3 sharp...etc. I don't mind modifying the code and possibly creating a PR, but I would appreciate some hints on where or how I should implement this. Thanks in advance.

**Comment by puranjayjain** [comment]
@XcrossD your initial thought process is spot on yes you would have to make a custom build.

You can start off here
https://github.com/puranjayjain/md-date-time-picker/blob/master/src/js/mdDateTimePicker.js#L503

take a look at `_initMinute` and `_initHour` that would be the ideal place to setup that logic along with `_initTimeDialog`

**Comment by XcrossD** [comment]
@puranjayjain Got it up and working, thanks! I wonder whether this is worth creating a PR. This feature is very specific IMO. What are your thoughts on this?

**Comment by puranjayjain** [comment]
You can create an official fork of the project and put a PR for the readme linking it. With a description of what it solves it might help future users looking for that specific problem :smile:

**Comment by XcrossD** [comment]
I'm not sure if this way of doing things is what you mentioned. Feel free to edit.
