### ISSUE TITLE
Got New issue, Date picking(value) is fine but i cant save the value. Got Error message like this..

### ISSUE THREAD

**Issue by Arunaki** [puranjayjain/md-date-time-picker#242]
# Issue Templates

- Search the currently opened issues and past issues before posting a new one.
- Escalate issues by making a reaction of :+1: at the first comment on the issue (the issue author's)
- Be clear and try to open an issue with one problem at a time (open multiple issues if you have multiple problems)

**Comment by Arunaki** [comment]
I am using MdDateTime picker in my sharepoint site, I am not getting any error message in Chrome and Firefox picking date and save. But when i'm using Internet Explorer and Edge browser, i am getting this error 

![image](https://user-images.githubusercontent.com/38925432/40332900-75fb692e-5d73-11e8-8ee9-867f6dae1a0a.png)

**Comment by puranjayjain** [comment]
Hi @Arunaki you will need to use polyfills as suggested in the docs for edge and IE. https://puranjayjain.github.io/md-date-time-picker/#documentation/ie
