### ISSUE TITLE
Dependencies not adequately listed in package.json

### ISSUE THREAD

**Issue by xeon826** [puranjayjain/md-date-time-picker#251]
So I install this plugin via npm, I look through [here](https://github.com/puranjayjain/md-date-time-picker/issues/16) and use `import mdDateTimePicker from 'md-date-time-picker/src/js/mdDateTimePicker';` along with the latter function, (quick note for me it's `dialog['time']` as opposed to `dialog.time()` but I wanted to point out that it does not install the required dependencies 

`    "babel-plugin-transform-es2015-modules-umd": "^6.24.1",
    "babel-plugin-transform-member-expression-literals": "^6.8.1",
    "babel-plugin-transform-merge-sibling-variables": "^6.9.4",
    "babel-plugin-transform-minify-booleans": "^6.9.4",
    "babel-plugin-transform-property-literals": "^6.9.4",`
Likely something to do with package.json?

**Comment by puranjayjain** [comment]
I'm not quite able to understand what you are pointing out here

**Comment by xeon826** [comment]
> I'm not quite able to understand what you are pointing out here

So I install this plugin via `npm install md-date-time-picker" but this is by no means the end of the story. Afterwards, it gives me the error 'Unknown plugin "transform-es3-member-expression-literals"', so I install that and it asks for several other plugins like the ones listed above. I also ended up having to create a .babelrc in the root dir with 
````
{
  "plugins": ["transform-es3-member-expression-literals"]
}
````
I'm not sure if this was necessary but it fails to compile if its not there so I guess so. I just wanted to point out that this is usually not the case with node modules as far as I know, usually they install their dependencies automatically.

**Comment by puranjayjain** [comment]
I think the babel dependencies have changed since the inception of this project and need to be fixed, can you raise a PR with your above fix? That would be really helpful 😄

**Comment by xeon826** [comment]
It's fixed.
