### ISSUE TITLE
`CustomEvent` is not supported in IE11 and lower

### ISSUE THREAD

**Issue by drwlrsn** [puranjayjain/md-date-time-picker#29]
I may have missed something, but when using the dist library on puranjayjain/md-date-time-picker@3fc44bac367c85e8347fe4692d44e313617a0da5 I needed to include a `CustomEvent` polyfill for IE11.

**Comment by puranjayjain** [comment]
I'll look into it @drwlrsn

**Comment by puranjayjain** [comment]
@drwlrsn 
the reason is because the v2.0.0 had a breaking change when the build tools changed and so won't directly be supporting custom events. However, I am adding the polyfill's link to the website which when included will resolve this issue.

**Comment by puranjayjain** [comment]
@drwlrsn check the new docs, it is resolved now. Feel free to reopen this issue or open a new one for troubles. :smile:
