### ISSUE TITLE
Problems when showing modal on mobile devices.

### ISSUE THREAD

**Issue by lockys** [puranjayjain/md-date-time-picker#3]
Thanks for your awesome work :)
I'm using your component in my project.
I found that there is a transparent area between the heading of the modal and body of the modal when running on mobile devices. (Test on both latest version chrome and safari on iPhone 5s, also happened in the responsive mode in the development console of Chrome and Safari.)

![2016-03-29 7 35 40](https://cloud.githubusercontent.com/assets/3911469/14106836/7d91e164-f5e6-11e5-9e0f-93b8ce9e460a.png)

Thank you.

**Comment by puranjayjain** [comment]
@lockys thanks for pointing out the issue, it seems to be a general bug related to portrait mode in the time picker dialog, a fix is on its way

**Comment by puranjayjain** [comment]
@lockys check if the issue is still persisting in the v1.0.1 release, if still found then :smile: feel free to reopen this issue.

**Comment by lockys** [comment]
it works great now :) thanks for your effort!
