### ISSUE TITLE
Uncaught TypeError: mdDateTimePicker is not a constructor

### ISSUE THREAD

**Issue by BennyAlex** [puranjayjain/md-date-time-picker#33]
I use Ember 2.4.5 and if I write 

> var dialog = new mdDateTimePicker({
>               type: 'date'
>             });

I get **'Uncaught TypeError: mdDateTimePicker is not a constructor'**
Any help?

**Comment by puranjayjain** [comment]
@BennyAlex Sorry I forgot to update this new api on the website.
You can now use the above like,

```
var dialog = new mdDateTimePicker.default({
        type: 'date'
 });
```

Also, please tell the results if this works with emberjs

**Comment by BennyAlex** [comment]
@puranjayjain Thanks, that works. But now I have the problem that the dialog looks unsharp:
On my site: 
![unsharp](https://cloud.githubusercontent.com/assets/17402724/14879996/bbc38548-0d2c-11e6-8cae-1e9f9add3259.png)

On your demo:
![sharp](https://cloud.githubusercontent.com/assets/17402724/14880001/c45527b6-0d2c-11e6-9e5f-1fd2fb69044c.png)

**Comment by puranjayjain** [comment]
@BennyAlex link for your site, if it's ok?
I guess the problem must be one or multiple of these:
1. The fonts must not be correctly included.
2. A css selector must be interfering with the dialog.

**Comment by BennyAlex** [comment]
@puranjayjain My app is only local avaible. I integrated the google fonts, md-date-time-picker/dist/fonts, d-date-time-picker/dist/fonts/RobotoTTF and d-date-time-picker/dist/images

**Comment by BennyAlex** [comment]
now it looks like:
![2016-04-28 12_06_28-timesheetfrontend](https://cloud.githubusercontent.com/assets/17402724/14882575/b62a46be-0d39-11e6-91c6-403d13098297.png)

just a bit unsharp anymore

**Comment by puranjayjain** [comment]
@BennyAlex if you are using the app mostly on chrome or other webkit based browsers you can try these css property on the unsharp font elements.

```
.element {
-webkit-font-smoothing:antialiased;
-moz-osx-font-smoothing:grayscale
}
```

or try them globally

```
* {
-webkit-font-smoothing:antialiased;
-moz-osx-font-smoothing:grayscale
}
```

**Comment by puranjayjain** [comment]
@BennyAlex was this issue resolved?

**Comment by puranjayjain** [comment]
Feel free to reopen this issue or open a new one if this persists
