### ISSUE TITLE
images folder: why not just use "Material icons"

### ISSUE THREAD

**Issue by mahnunchik** [puranjayjain/md-date-time-picker#37]
Hi @puranjayjain 

I've faced with the fact that you are using the images for icons.

Why not just use material icons module:
- https://github.com/google/material-design-icons
- https://design.google.com/icons/

**Comment by puranjayjain** [comment]
@mahnunchik good suggestion but I wanted the dependency to be minimum. I was eventually shifting to a sprite sheet for more compatibility and lesser size of images. I'm not sure if we need to add a full iconset for just two icons.

**Comment by mahnunchik** [comment]
You may use just `<` and `>` symbols to reduce amount of dependencies and size to minimum 😉 

Also I find it is useful to have instruction how to replace symbols by icons from full icon set (for who already use mdl with full icon set)

**Comment by puranjayjain** [comment]
@mahnunchik send a PR? :grin:

**Comment by mh-cbon** [comment]
I have a commit for that matter. It makes handle content configurable so you could put material icon markups and adjust their styles with a bit of css.

See https://github.com/mh-cbon/md-date-time-picker/commit/72b343c0f6434c277d6d4e756fc396bb994fb062

If that looks fine, i can make a pr.

**Comment by puranjayjain** [comment]
Go ahead start a PR

**Comment by SabineMa** [comment]
is it possible now to use icons from the mdl icons set instead of the < and > symbols?
I did not found that in the documentation.

**Comment by puranjayjain** [comment]
Well, you could use them instead of < and > but not via any options. For that, you would have to edit the source files see https://github.com/puranjayjain/md-date-time-picker/blob/master/src/js/mdDateTimePicker.js#L51. Just replace them with your icon font definition e.g <i class="icon-map"></i>

**Comment by SabineMa** [comment]
it was also possible via options thanks for the hint in the source file, that helped to find the parameter names. Would be nice to have that in the documentation:
prevHandle:'<i class="material-icons">keyboard_arrow_left</i>',nextHandle:'<i class="material-icons">keyboard_arrow_right</i>'
![bildschirmfoto 2016-12-22 um 13 05 03](https://cloud.githubusercontent.com/assets/13763544/21425093/4f4be42e-c847-11e6-9656-d843d6abbc0a.png)

**Comment by puranjayjain** [comment]
I just sifted through the entire PR #141 I found it was also an option to change the next and previous button, I'll add that to the docs once that one gets merged
