### ISSUE TITLE
Add events

### ISSUE THREAD

**Issue by cmfcmf** [puranjayjain/md-date-time-picker#4]
It is currently not possible to detect when the datepicker / timepicker is closed (i.e. the cancel / ok button is clicked). It would be great to have an event fired when the picker is closed.

**Comment by puranjayjain** [comment]
@cmfcmf I was also thinking about it and other possible use cases. I'm adding events in the next release.

**Comment by puranjayjain** [comment]
Feel free to reopen this issue or open a new one if this persists
