### ISSUE TITLE
Cannot read property 'firstChild' of null

### ISSUE THREAD

**Issue by blackcoliver** [puranjayjain/md-date-time-picker#45]
Hi @puranjayjain,

I run the component in Aurelia, but it gives an error: Cannot read property 'firstChild' of null.

Regards.

**Comment by puranjayjain** [comment]
@blackcoliver can you tell me about the aurelia a little bit? I don't have any experience with it and never heard of it before :disappointed_relieved:

**Comment by puranjayjain** [comment]
This issue is being closed due to no response from the first reponder for more than 14 days (two weeks) Please provide the information that was asked for and get the issue reopened
