### ISSUE TITLE
Update docs in https://puranjayjain.github.io/md-date-time-picker/#documentation/time

### ISSUE THREAD

**Issue by delagen** [puranjayjain/md-date-time-picker#60]
*time & trigger is not a method
*update example with above changes
and may be others )

**Comment by puranjayjain** [comment]
@Delagen Can you please explain this question I didn't understand you completely.
Did you mean https://puranjayjain.github.io/md-date-time-picker/#documentation/trigger1

**Comment by delagen** [comment]
![2016-05-25 12 53 14](https://cloud.githubusercontent.com/assets/783335/15535970/334e9426-2278-11e6-9dc6-264b839b3639.png)
![2016-05-25 12 54 09](https://cloud.githubusercontent.com/assets/783335/15535971/3369b1fc-2278-11e6-9579-1b531ff35c67.png)
![2016-05-25 12 55 14](https://cloud.githubusercontent.com/assets/783335/15535972/337a5afc-2278-11e6-9c9e-0440fbf83222.png)

**Comment by puranjayjain** [comment]
@Delagen I'll look into this error. There must be some inconsistency in the docs
