### ISSUE TITLE
Improvement in 24-format layout

### ISSUE THREAD

**Issue by db-dblank** [puranjayjain/md-date-time-picker#62]
Divide hours in two circles, outer circle with hours from 1 to 12 and inner circle with hours from 13 to 00.

This is how the picker is on Android apps, this way the hours would be more spaced and better for clicking, specially on mobile devices. And it looks better. =)

![calendar-timepicker](https://cloud.githubusercontent.com/assets/15021504/15543423/3a50479a-226b-11e6-8ac2-8b880e5d236b.jpg)

**Comment by puranjayjain** [comment]
@db-dblank That's a nice suggestion but would require major changes in the component which I'm not sure I would be able to do. Moreover, the material design spec is not clear on how to deal with the 24 hour mode at the moment, so it can be left as is. 

However, if you want to use this specific style right now you can implement it in your fork. I will gladly point to it for people with custom requirements (please tell me if you do complete it)

Meanwhile this issue will remain parked.

If there is enough traction regarding this issue, it can be escalated. A PR will later be merged in the future for this matter.

**Comment by alegag** [comment]
This has been implemented in PR #134, it could be closed.

@puranjayjain @db-dblank

**Comment by puranjayjain** [comment]
@alegag pls remind me to add your name to contributors in case I forget and thanks again
