### ISSUE TITLE
Is it possible to select the future dates? Currently I am only able to select dates on or before current day.

### ISSUE THREAD

**Issue by mbashiq** [puranjayjain/md-date-time-picker#65]
# Issue Templates
- Search the currently opened issues and past issues before posting a new one.
- Escalate issues by making a reaction of :+1: at the first comment on the issue (the issue author's)
- Be clear and try to open an issue with one problem at a time (open multiple issues if you have multiple problems)

**Comment by puranjayjain** [comment]
@mbashiq that is possible only if you pass this option: (with how much in the future you want it to be selectable)
https://puranjayjain.github.io/md-date-time-picker/#documentation/future

**Comment by mbashiq** [comment]
Thank you Very Much.
When I open the above provided link it opens for an instant and goes to main page.
Finally i had to take a screenshot. Thanks though, it solved my problem.

**Comment by puranjayjain** [comment]
You're welcome :smile:
