### ISSUE TITLE
Add support for other locales

### ISSUE THREAD

**Issue by troxler** [puranjayjain/md-date-time-picker#70]
- Date format of
  - Selected date
  - Current month
- First day of week (in many locales, Monday is the first day of week)

**Comment by puranjayjain** [comment]
@troxler nice suggestions though I would not be able to attempt it at this time. Would be awesome if you or someone could start a PR. keeping this open for reference. :)

**Comment by troxler** [comment]
@puranjayjain Thanks for the quick reply. Currently, my time resources are scarce as well. I might get back to that in a couple of weeks, though. If anybody else would like to look into it before that, feel free.

**Comment by netTrek** [comment]
Sent you a PR
Regards Saban
