### ISSUE TITLE
Projects / App / Website Showcase Requests

### ISSUE THREAD

**Issue by puranjayjain** [puranjayjain/md-date-time-picker#8]
Feel free to add your project/app/link to this issue to add it to website showcase section which is coming soon!

**Comment by danghongthanh** [comment]
Now when i tried npm install md-date-time-picker, i still get old version("md-date-time-picker": "^1.2.0").
Also, Do we have example to use with Webpack?

**Comment by puranjayjain** [comment]
@danghongthanh it's because the module is not yet released with v2.0.0. I'll be adding some usage examples with webpack on the website soon
