### ISSUE TITLE
Hide/show dialog methods

### ISSUE THREAD

**Issue by jonnnnyw** [puranjayjain/md-date-time-picker#89]
Would it be possible to expose the hide and show dialog methods in the public API? Having just a toggle method does not work for all use cases. An example is when tabbing through multiple date fields things get messy with just a toggle method.

**Comment by puranjayjain** [comment]
I'll do that some time when I get free, btw good suggestion.

**Comment by alegag** [comment]
This has been implemented in PR #134.  It could be closed.

@puranjayjain @jonnnnyw

**Comment by puranjayjain** [comment]
Thanks @alegag closing it
