### ISSUE TITLE
Doesn't appear to work correctly in Internet Explorer

### ISSUE THREAD

**Issue by warrior7981** [puranjayjain/md-date-time-picker#9]
This appears to be a well designed component and is exactly what I'm looking for but I'm having some issues in IE.

I tested this in Internet Explorer 11.  (Browser support says: Internet Explorer 8.  I assume this is supposed to mean 8+.)

Opening the included demo.html in IE 11 results in all of the dialogs opening immediately.  If I correct that issue by creating the mdDateTimePickers right before performing the toggle, the time picker does not work correctly.

**Comment by puranjayjain** [comment]
Thanks for pointing it out i'll look into it.

**Comment by puranjayjain** [comment]
@warrior7981 the issue is now addressed in the release 1.1.1 for ie 11 test it on lower versions for any problems and reopen this issue or a new one if it occurs

**Comment by warrior7981** [comment]
Thanks!
